apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - port: 8080        # Service port
      targetPort: 8080  # Container port
      nodePort: 30003   # NodePort (must be 30000–32767)
